export const LOGGED_USER = "LOGGED_USER";
export const SHOW_ALL_USERS = "SHOW_ALL_USERS";
export const SHOW_ALL_QUESTIONS = "SHOW_ALL_QUESTIONS";
export const SHOW_ANSWERED_QUESTIONS  = "SHOW_ANSWERED_QUESTIONS";
